import LanguageDictionaryInterface from "../types/language";

const EnglishTextsList: LanguageDictionaryInterface = {
  aboutDeveloperText: "About the developer",
  aboutText: "About",
  appVersionText: "App Version:",
  buyProVersionText: "Buy PRO Version",
  canRepeatCharactersText: "Character Repetition",
  changeLanguageText: "Change language",
  closeText: "Close",
  generalText: "General",
  generatePasswordText: "Generate Password",
  generatedPasswordText: "Generated Password",
  lowercaseLettersText: "Lowercase Letters",
  mediumPasswordText: "Your password is moderately strong!",
  modifyLanguageText: "Change language",
  numbersText: "Numbers",
  passwordLengthLimitText:
    "Invalid number of characters to generate your new password!",
  passwordLengthText: "Password Length",
  restorePurchaseText: "Restore purchase",
  settingsText: "Settings",
  socialMediaText: "Social Media",
  specialCharactersText: "Special Characters",
  storeText: "Store",
  strongPasswordText: "Your password is very strong!",
  successCopyContent: "Content copied successfully!",
  uppercaseLettersText: "Uppercase Letters",
  weakPasswordText: "Your password is very weak/vulnerable!",
};

const PortugueseTextsList: LanguageDictionaryInterface = {
  aboutDeveloperText: "Sobre a desenvolvedora",
  aboutText: "Sobre",
  appVersionText: "Versão do App:",
  buyProVersionText: "Comprar a versão PRO",
  canRepeatCharactersText: "Repetição de Caracteres",
  changeLanguageText: "Mudar idioma",
  closeText: "Fechar",
  generalText: "Geral",
  generatePasswordText: "Gerar Senha",
  generatedPasswordText: "Senha Gerada",
  lowercaseLettersText: "Letras Minúsculas",
  mediumPasswordText: "Sua senha é moderadamente forte!",
  modifyLanguageText: "Alterar idioma",
  numbersText: "Números",
  passwordLengthLimitText:
    "Quantidade de caracteres inválido para gerar sua nova senha!",
  passwordLengthText: "Tamanho da Senha",
  restorePurchaseText: "Restaurar compra",
  settingsText: "Configurações",
  socialMediaText: "Redes Sociais",
  specialCharactersText: "Caracteres Especiais",
  storeText: "Loja",
  strongPasswordText: "Sua senha é muito forte!",
  successCopyContent: "Conteúdo copiado com sucesso!",
  uppercaseLettersText: "Letras Maiúsculas",
  weakPasswordText: "Sua senha é muito fraca/vulnerável!",
};

const SpanishTextsList: LanguageDictionaryInterface = {
  aboutDeveloperText: "Acerca del desarrollador",
  aboutText: "Acerca",
  appVersionText: "Versión de la Aplicación:",
  buyProVersionText: "Comprar la versión PRO",
  canRepeatCharactersText: "Repetición de Caracteres",
  changeLanguageText: "Cambiar idioma",
  closeText: "Cerrar",
  generalText: "General",
  generatePasswordText: "Generar Contraseña",
  generatedPasswordText: "Contraseña Generada",
  lowercaseLettersText: "Letras Minúsculas",
  mediumPasswordText: "¡Tu contraseña es moderadamente fuerte!",
  modifyLanguageText: "Cambiar idioma",
  numbersText: "Números",
  passwordLengthLimitText:
    "¡Cantidad de caracteres no válida para generar su nueva contraseña!",
  passwordLengthText: "Longitud de la Contraseña",
  restorePurchaseText: "Restaurar compra",
  settingsText: "Ajustes",
  socialMediaText: "Redes Sociales",
  specialCharactersText: "Caracteres Especiales",
  storeText: "Almacenar",
  strongPasswordText: "¡Tu contraseña es muy fuerte!",
  successCopyContent: "¡Contenido copiado exitosamente!",
  uppercaseLettersText: "Letras Mayúsculas",
  weakPasswordText: "¡Su contraseña es muy débil/vulnerable!",
};

export { EnglishTextsList, PortugueseTextsList, SpanishTextsList };
